Final_Project_BE/m1c2cmp/config/routes.rb
Rails.application.routes.draw do
  get 'imageupload/index'

  get 'imageupload/new'

  get 'imageupload/create'

  get 'imageupload/destroy'

  resources :likes
  resources :users
  resources :companies

  root 'companies#index'

end

Final_Project_BE/m1c2cmp/app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :user
	has_many :likes
	mount_uploader :logo, AttachmentUploader
end
	

Final_Project_BE/m1c2cmp/app/models/imageupload.rb
class Imageupload < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  	validates :name, presence: true # Make sure the owner's name is present.
end

Final_Project_BE/m1c2cmp/app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :company
	belongs_to :user
end

Final_Project_BE/m1c2cmp/app/models/user.rb
class User < ActiveRecord::Base
	has_many :likes
	has_many :companies
end

Final_Project_BE/m1c2cmp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Final_Project_BE/m1c2cmp/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :geography, :hyperlocal, :commission, :category, :delivery, :logo)
    end
end

Final_Project_BE/m1c2cmp/app/controllers/imageupload_controller.rb
class ImageuploadController < ApplicationController
  def index
  	@imageupload=Imageupload.all
  end

  def new
  	@imageupload=Imageupload.new
  end

  def create
  	@imageupload=Imageupload.new(imageupload_params)

  	if @imageupload.save
  		redirect_to_imageuploads_path, notice: "The Image has been uploaded."
  	else
  		render "new"
  	end
  end

  def destroy
  	@imageupload=Imageupload.find(params[:id])
  	@imageupload.destroy
  	redirect_to_imageuploads_path, notice: "The Image has been deleted."
  end
end

Final_Project_BE/m1c2cmp/app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

Final_Project_BE/m1c2cmp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :name, :email, :location, :user_likes)
    end
end

Final_Project_BE/m1c2cmp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Final_Project_BE/m1c2cmp/app/helpers/application_helper.rb
module ApplicationHelper
end

Final_Project_BE/m1c2cmp/app/helpers/companies_helper.rb
module CompaniesHelper
end

Final_Project_BE/m1c2cmp/app/helpers/imageupload_helper.rb
module ImageuploadHelper
end

Final_Project_BE/m1c2cmp/app/helpers/likes_helper.rb
module LikesHelper
end

Final_Project_BE/m1c2cmp/app/helpers/users_helper.rb
module UsersHelper
end

Final_Project_BE/m1c2cmp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Final_Project_BE/m1c2cmp/app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :logo %><br>
    <%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :geography %><br>
    <%= f.text_area :geography %>
  </div>
  <div class="field">
    <%= f.label :hyperlocal %><br>
    <%= f.check_box :hyperlocal %>
  </div>
  <div class="field">
    <%= f.label :commission %><br>
    <%= f.text_field :commission %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_area :category %>
  </div>
    <div class="field">
    <%= f.label :delivery %><br>
    <%= f.check_box :delivery %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Final_Project_BE/m1c2cmp/app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

Final_Project_BE/m1c2cmp/app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mobile-first C2C Marketplaces</h1>


<!-- start database html -->

<div class="flex-table">
 
  <div class="database_table_body">
    <% @companies.each do |company| %>
     <%= div_for company, :class => "large_rowBox" do %>
      <div id="database_body">
        <div class="database_table_image"><%= image_tag(company.logo_url, width:90, height:70) %>
        </div>
           <%= div_for company, :class => "rowBox" do %>
        <div class="database_global"> 
          <div class="database_title">
              Name:
          </div>  
          <div class="database_input">
              <%= company.name %>
          </div>
        </div>
        <div class="database_global"> 
          <div class="database_title">
            Geography:
          </div> 
          <div class="database_input">
            <%= company.geography %>
          </div>
        </div>
        <div class="database_global"> 
          <div class="database_title">
            Hyperlocal:
          </div>
          <div class="database_input"> 
            <%= company.hyperlocal %>
          </div>
        </div>
        <div class="database_global"> 
          <div class="database_title">
            Commission:
          </div> 
          <div class="database_input">
            <%= company.commission %>
          </div>
        </div>
        <div class="database_global"> 
          <div class="database_title">
            Category:
          </div>
          <div class="database_input">
          <%= company.category %>
          </div>
        </div>
        <div class="database_global">
          <div class="database_title">
            Delivery:
          </div>
          <div class="database_input">
            <%= company.delivery %>
          </div>
        </div>
        <div class="modify_container">
          <div class="modify">
            <%= link_to 'Show', company %>
          </div>
          <div class="modify">
            <%= link_to 'Edit', edit_company_path(company) %></div>
          <div class="modify">
            <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div> 
        </div>
      </div>
      <% end %>
      <% end %>
    <% end %>
  </div>

</div>

<!-- end database layout -->

<br>

<%= link_to 'New Company', new_company_path %>

Final_Project_BE/m1c2cmp/app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

Final_Project_BE/m1c2cmp/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Geography:</strong>
  <%= @company.geography %>
</p>

<p>
  <strong>Hyperlocal:</strong>
  <%= @company.hyperlocal %>
</p>

<p>
  <strong>Commission:</strong>
  <%= @company.commission %>
</p>

<p>
  <strong>Category:</strong>
  <%= @company.category %>
</p>

<p>
  <strong>Delivery:</strong>
  <%= @company.delivery.to_s %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @company.logo.to_s %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

Final_Project_BE/m1c2cmp/app/views/imageupload/create.html.erb
<h1>Imageupload#create</h1>
<p>Find me in app/views/imageupload/create.html.erb</p>

Final_Project_BE/m1c2cmp/app/views/imageupload/destroy.html.erb
<h1>Imageupload#destroy</h1>
<p>Find me in app/views/imageupload/destroy.html.erb</p>

Final_Project_BE/m1c2cmp/app/views/imageupload/index.html.erb
<h1>Imageupload#index</h1>
<p>Find me in app/views/imageupload/index.html.erb</p>

Final_Project_BE/m1c2cmp/app/views/imageupload/new.html.erb
<h1>Imageupload#new</h1>
<p>Find me in app/views/imageupload/new.html.erb</p>

Final_Project_BE/m1c2cmp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>M1c2cmp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="header">
      <a href="#" class="hamburgermenu"></a>
        <div class="nav">
          <ul class="header_ul">
            <li>
              <a href="#main_content_2">Test2</a>
            </li>
            <li>
              <a href="<span id="main_con"></span>tent_3">Test3</a>
            </li>
            <li>
              <a href="#main_content_4">Test4</a>
            </li>
            <li>
              <a href="/users">User</a>
            </li>
          </ul>
        </div>  
    </div>

	<div class="database">
		<%= yield %>
	</div>
</body>
</html>

Final_Project_BE/m1c2cmp/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :user_likes %><br>
    <%= f.text_area :user_likes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Final_Project_BE/m1c2cmp/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Final_Project_BE/m1c2cmp/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Name</th>
      <th>Email</th>
      <th>Location</th>
      <th>User likes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.location %></td>
        <td><%= user.user_likes %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Final_Project_BE/m1c2cmp/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

Final_Project_BE/m1c2cmp/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>User likes:</strong>
  <%= @user.user_likes %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

Final_Project_BE/m1c2cmp/app/views/welcome/index.html.erb
<! DOCTYPE html>
<html>
<link rel="stylesheet" type="text/css" href="application.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- <script src="index.js"></script> -->

<div class="header">
      <a href="#d" class="hamburgermenu"></a>
        <div class="nav">
          <ul class="header_ul">
    	      <li>
              <a href="#main_content_2">Test2</a>
            </li>
    	      <li>
              <a href="#main_content_3">Test3</a>
            </li>
    	      <li>
              <a href="#main_content_4">Test4</a>
            </li>
            <li>
              <a href="#main_content_5">Test5</a>
            </li>
        	</ul>
      	</div>  
    </div>


</html>